language: java
jdk:
    # - oraclejdk8
    - openjdk7
dist: trusty
branches:
    except:    
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
install:
    - true
script:
    - ./mvnw clean install -pl maven/impl-maven-embedded -am -Dtest=org.jboss.shrinkwrap.resolver.impl.maven.embedded.* -Dsurefire.failIfNoSpecifiedTests=false
